FROM openjdk:17-slim

WORKDIR /app

COPY src/AdvancedMotorInsuranceSystem /app/src/AdvancedMotorInsuranceSystem

RUN javac /app/src/AdvancedMotorInsuranceSystem/*.java

CMD ["java", "-cp", "/app/src", "AdvancedMotorInsuranceSystem.MotorVehicleInsuranceSystem"]
